Handle absolute paths when specifie reporter's output path in arguments
yopeso/Taylor pull request #49
Opened 2016-12-21 21:09 UTC by mihai8804858

Slightly refactored reporter coordinators

2016-12-22 12:55 UTC, lexorus reviewed
The mentioned issue itself is fixed.

2016-12-22 12:55 UTC, lexorus commented on TaylorIntegrationTests/ReporterComparator.swift
> +    func compareReporter(atPath path1: String, withReporterAtPath path2: String) -> Bool {
This is the function that gets two paths, then parses this files to get violations, then compares each violation through iteration. 
All this is happening in `compareReporter(atPath:withReporterAtPath:)` function of `ReporterComparator` class.
The Reporter word leads to a delusion here(we also have reporters in this project).
Can you think about a better name, like `compareViolations`, or for a better place/implementation of this functionality(extension)?

2016-12-22 12:55 UTC, lexorus commented on TaylorFramework/Modules/temper/Output/OutputCoordinator.swift
> +    private func writeOutput(with violations: [Violation], reporter: Reporter) {
I think we can get rid of the `Output` word here.

2016-12-22 13:04 UTC, lexorus commented
Also, there is a Typo in commit:
Handle absolute paths when _**specifie**_ reporter's output path in arguments

2016-12-22 14:08 UTC, mihai8804858 commented on TaylorIntegrationTests/ReporterComparator.swift
> +    func compareReporter(atPath path1: String, withReporterAtPath path2: String) -> Bool {
This class takes 2 paths to reports and compare them. I'm not interested how it compares the reports, it's his problem. Also, If I would see `compareViolations` function I would think that I should give it an array of `Violation`.

2016-12-22 14:16 UTC, lexorus commented on TaylorIntegrationTests/ReporterComparator.swift
> +    func compareReporter(atPath path1: String, withReporterAtPath path2: String) -> Bool {
Then, maybe will be better to name it `compareReport(atPath:withReportAtPath:)` aka **report** and not **reporter**?

2016-12-22 14:26 UTC, mihai8804858 commented on TaylorIntegrationTests/ReporterComparator.swift
> +    func compareReporter(atPath path1: String, withReporterAtPath path2: String) -> Bool {
Already done that.

2016-12-22 19:18 UTC, thelvis4 commented
@mihai8804858 Tests are failing 😢

2016-12-22 21:28 UTC, mihai8804858 commented
@thelvis4 Don't know why 😢 Have you tried to run the tests on your machine? On my machine and on @lexorus's the tests are passing.

2016-12-27 11:50 UTC, thelvis4 commented
@mihai8804858 @lexorus Checks are failing because code coverage decreased. 😢

2016-12-27 13:19 UTC, thelvis4 commented on TaylorFramework/Modules/temper/Output/PMDCoordinator.swift
> +            violations.filter { $0.path == path }
It seems like we do a lot of iteration here. A big number of violations can lead to a computation time growth.
One way we can reduce the numbers of loops is by iterating through violations (just once), group them into a dictionary that uses paths as keys:
```swift
private typealias ViolationsMap = [Path: [Violation]]

final class PMDCoordinator: WritingCoordinator {
    
    func writeViolations(_ violations: [Violation], atPath path: String) {
        FileManager().removeFileAtPath(path)
        let map = mapViolations(violations)
        let xml = generateXML(from: map)
        let xmlData = xml.xmlData(withOptions: Int(XMLNode.Options.nodePrettyPrint.rawValue))
        do {
            try xmlData.write(to: URL(fileURLWithPath: path), options: .atomic)
        } catch let error {
            let message = "Error while writing XML object at path: " + path + "\n" +
                "Reason: " + error.localizedDescription
            Printer(verbosityLevel: .error).printError(message)
        }
    }
    
    private func mapViolations(_ violations: [Violation]) -> ViolationsMap {
        return violations.reduce([Path : [Violation]]()) { result, violation in
            let path = violation.path
            
            // Add violation to the group with the same path
            var violations = result[path] ?? []
            violations.append(violation)
            
            // Update the result
            var nextResult = result
            nextResult[path] = violations
            
            return result
        }
    }
    
    private func generateXML(from violationsMap: ViolationsMap) -> XMLDocument {
        let xml = XMLDocument(rootElement: XMLElement(name: "pmd"))
        xml.version = "1.0"
        xml.characterEncoding = "UTF-8"
        
        let fileElements = violationsMap.map(generateFileElement)
        xml.rootElement()?.addChildren(fileElements)
        
        return xml
    }
    
    private func generateFileElement(path: Path, violations: [Violation]) -> XMLElement {
        let element = XMLElement(name: "file")
        let attribute = XMLNode(kind: .attribute)
        attribute.setValue(path, forKey: "name")
        element.addAttribute(attribute)
        
        violations.forEach { element.addChild($0.toXMLElement()) }
        
        return element
    }
}

extension XMLElement {
    func addChildren(_ children: [XMLElement]) {
        children.forEach { child in
            addChild(child)
        }
    }
}
```
What do you think?

2016-12-27 13:24 UTC, thelvis4 commented on TaylorIntegrationTests/TaylorIntegrationTests.swift
> +    var taylorExecutablePath : String {
How about `executableFilePath`?
If we rename the tool, we don't want to be needed to make too many changes.

2016-12-27 13:29 UTC, thelvis4 requested changes

2016-12-27 13:29 UTC, thelvis4 commented on TaylorIntegrationTests/TaylorIntegrationTests.swift
> +    fileprivate func runTaylorWithArguments(_ arguments: String...) {
`runWithArguments`?

2016-12-27 13:29 UTC, thelvis4 commented on TaylorIntegrationTests/TaylorIntegrationTests.swift
> +            context("when specifie report with relative path") {
Typo here at `specifie`

2016-12-27 13:29 UTC, thelvis4 commented on TaylorIntegrationTests/TaylorIntegrationTests.swift
> +            context("when specifie report with absolute path") {
Same tipo (`specifie`) here 😉

2016-12-27 22:56 UTC, mihai8804858 commented on TaylorIntegrationTests/TaylorIntegrationTests.swift
> +            context("when specifie report with absolute path") {
Typo here: `tipo` -> `typo` 😉

2016-12-27 23:01 UTC, mihai8804858 commented on TaylorFramework/Modules/temper/Output/PMDCoordinator.swift
> +            violations.filter { $0.path == path }
I think you did a good job! 👍

2016-12-27 23:32 UTC, thelvis4 commented on TaylorIntegrationTests/TaylorIntegrationTests.swift
> +            context("when specifie report with absolute path") {
🤣

2016-12-28 08:51 UTC, thelvis4 commented
@mihai8804858 There is a typo in the commit message. Could you please fix it?

2016-12-28 08:57 UTC, thelvis4 requested changes

2016-12-28 08:57 UTC, thelvis4 commented on TaylorFrameworkTests/TemperTests/NSFileManagerTests.swift
> +            it("should't remove file at path if it's not deleatable") {
There is no such word `deleatable`. You can use `deletable` or `delible`, but I recommend to use  `removable` here as it's less pretentious.

2016-12-28 08:57 UTC, thelvis4 commented on TaylorFrameworkTests/TemperTests/NSFileManagerTests.swift
> +            it("should't remove file at path if it's not deleatable") {
Typo: `should't`

2016-12-28 09:25 UTC, mihai8804858 commented on TaylorFrameworkTests/TemperTests/NSFileManagerTests.swift
> +            it("should't remove file at path if it's not deleatable") {
There is a method in 'FileManager' called 'isDeleatableFileAtPath', I throught there is such word. 🙂

2016-12-28 10:25 UTC, mihai8804858 commented
@thelvis4 Fixed typos.

2016-12-28 19:15 UTC, thelvis4 commented
@mihai8804858  It seems like we introduced a bug here.
Before we had
```xml
<file name="/Some/path/to/file.swift">
```
but now we have
```xml
<file /Some/path/to/file.swift="">
```
Could you please investigate and also write some tests to make sure the bug is fixed and we won't have regressions?

2016-12-28 19:17 UTC, thelvis4 requested changes

2016-12-28 19:17 UTC, thelvis4 commented on TaylorFrameworkTests/TemperTests/NSFileManagerTests.swift
>              it("should't remove directory at path") {
It seems like we have the same typo here: `should't`

2016-12-28 20:10 UTC, mihai8804858 commented
@thelvis4 Done.

2016-12-28 20:19 UTC, thelvis4 approved these changes

2016-12-28 20:23 UTC, thelvis4 commented
@mihai8804858 How about the issue with `file` element? It's still reproducing to me.

2016-12-28 22:22 UTC, mihai8804858 commented
Oops, I missed that comment. 😕

2016-12-29 09:49 UTC, thelvis4 commented
@mihai8804858 Thanks for working on this! 👍 
You just made `Taylor` better! 👧 😊

2016-12-29 09:50 UTC, merged